### ISSUE TITLE
Train another dataset, generate only contact,

### ISSUE THREAD

**Issue by jyhflash** [stevenlsw/contactgen#13]
Hi, May I ask if it is possible to train only the contacts and generate contact_labels? I used another dataset for training and only generated possible contact information, but found that the effect was not very good. Is it due to the dataset? May I ask if the number of contact_gt in your dataset, that is, the number of labels for each GT, is relatively random or within a certain range, or if the network parameters need to be modified (I have already commented out the part_vae and uv_vae at the end, only training contact_vae)

**Comment by stevenlsw** [comment]
Hi,

Thanks for the interest in our work. You should able to train the contact map only on custom datasets. Presented in **Sec.4**. the contact value is between [0,1] in continuous form, so each grasping should have a unique contact map. For a given object, there could be multiple contact maps given different grasping ways of the object.  So that is why we model it by VAE. To train the VAE, you need to balance between the reconstruction loss and KL loss. Hope that helps.

**Comment by jyhflash** [comment]
Thank you very much for your reply，really thankful, I will try it.
